app: vjepa
nodes: 16
tasks_per_node: 8
data:
  dataset_type: VideoDataset
  datasets:
    - /content/SSv2_train_probe_filelist.csv
    # - /your_path_to_ssv2_csv_file_index.csv
    # - /your_path_to_howto100m_csv_file_index.csv
  decode_one_clip: true
  batch_size: 24
  # batch_size: 48
  num_clips: 1
  num_frames: 16
  tubelet_size: 2
  sampling_rate: 4
  crop_size: 224
  patch_size: 16
  pin_mem: true
  num_workers: 12
  filter_short_videos: false
  clip_duration: null
data_aug:
  auto_augment: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 0.3
  - 1.0
  reprob: 0.0
logging:
  folder: /content/drive/MyDrive/jepa/output_dir/videoMamba2T_pred_SSv2_v2
  write_tag: jepa
loss:
  loss_exp: 1.0
  reg_coeff: 0.0
mask:
  - aspect_ratio:
      - 0.75
      - 1.5
    num_blocks: 8
    spatial_scale:
      - 0.15
      - 0.15
    temporal_scale:
      - 1.0
      - 1.0
    max_temporal_keep: 1.0
    max_keep: null
  - aspect_ratio:
      - 0.75
      - 1.5
    num_blocks: 2
    spatial_scale:
      - 0.7
      - 0.7
    temporal_scale:
      - 1.0
      - 1.0
    max_temporal_keep: 1.0
    max_keep: null
meta:
  load_checkpoint: true
  read_checkpoint: null
  seed: 234
  eval_freq: 5
  # use_sdpa: true
  # dtype: bfloat16
  dtype: float32
model:
  model_name: videomamba_tiny
  pred_depth: 12
  pred_embed_dim: 144
  pred_head_dim: 72
  uniform_power: true
  use_mask_tokens: true
  zero_init_mask_tokens: true
optimization:
  ipe: 300
  ipe_scale: 1.25
  clip_grad: 10.0
  weight_decay: 0.1
  final_weight_decay: 0.4
  epochs: 300
  accumulation_steps: 4
  warmup: 20
  start_lr: 1.0e-06
  lr: 0.00001875
  final_lr: 8.0e-07
  ema:
  - 0.998
  - 1.0
  # eps: 1.0e-06
  # betas:
  # - 0.9
  # - 0.98
